### ISSUE TITLE
Return `int` from `main`

### ISSUE THREAD

**Issue by jglick** [jenkinsci-cert/security3430-workaround#1]
https://github.com/daniel-beck/security3430-workaround/blob/9efdc47a7d82396553dddba50bb7769d575aa466/src/main/java/io/jenkins/security/Security3430Workaround.java#L101 should return `int` (0 for success, 1 for failure).

**Comment by daniel-beck** [comment]
To clarify, adding `System#exit` calls? Because there's no `int main` in Java.

**Comment by jglick** [comment]
Uh yeah I guess, must have been a long time since I wrote a `main` method!

**Comment by daniel-beck** [comment]
https://github.com/daniel-beck/security3430-workaround/commit/4a98263358de86d0e07ea30bf686840905f1648b
