### ISSUE TITLE
`innerTransform` might throw `ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by jglick** [jenkinsci-cert/security3430-workaround#2]
From code inspection, https://github.com/daniel-beck/security3430-workaround/blob/9efdc47a7d82396553dddba50bb7769d575aa466/src/main/java/io/jenkins/security/Security3430Workaround.java#L76-L78 looks like it would throw an exception rather than returning `null` if the needle were not found but parts of it matched at the end. Unlikely but thought I would mention it. https://stackoverflow.com/a/20980266/12916 etc.

**Comment by daniel-beck** [comment]
Addressed in https://github.com/daniel-beck/security3430-workaround/commit/8233b2fdfa13c9891e31da1af023202d51848cee
